import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import { Providers } from "./providers";
import NavbarMenu from "@/components/ui/navbar-menu";
import { Toaster, toast } from "sonner";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <Providers>
            <NextUIProvider>
              <StackProvider app={stackServerApp}>
                <StackTheme>
                  <NavbarMenu />
                  {children}
                </StackTheme>
              </StackProvider>
            </NextUIProvider>
          </Providers>
          <Toaster richColors />
        </Suspense>
      </body>
    </html>
  );
}
